describe('Add Contact Test', () => {
    it('Can add a new contact', () => {

      let random = Math.floor(Math.random() * 1000)

      cy.visit('https://thinking-tester-contact-list.herokuapp.com')
      cy.get('#email').type('alba1@fake.com')
      cy.get('#password').type('Atest123456')
      cy.get('#submit').click()
      cy.get('#add-contact').click()
      cy.get('#firstName').type('User1' + random)
      cy.get('#lastName').type('Test1')
      cy.get('#birthdate').type('2000-03-06')
      cy.get('#email').type('user1test@fake.com')
      cy.get('#phone').type('622365698')
      cy.get('#submit').click()

      cy.contains('User1' + random + ' Test1').click()
      cy.get('#firstName').should('contain', `User1${random}`)
      cy.get('#lastName').should('contain', 'Test1')
      cy.get('#birthdate').should('contain', '2000-03-06')
      cy.get('#email').should('contain', 'user1test@fake.com')
      cy.get('#phone').should('contain', '622365698')

      cy.get('#delete').click()
      cy.on('window:confirm', () => true)
    })

    it('Can add another contact', () => {

      let random = Math.floor(Math.random() * 1000)

      cy.visit('https://thinking-tester-contact-list.herokuapp.com')
      cy.get('#email').type('alba1@fake.com')
      cy.get('#password').type('Atest123456')
      cy.get('#submit').click()
      cy.get('#add-contact').click()
      cy.get('#firstName').type('User2' + random)
      cy.get('#lastName').type('Test2')
      cy.get('#birthdate').type('2000-10-28')
      cy.get('#email').type('user2test@fake.com')
      cy.get('#phone').type('665983655')
      cy.get('#street1').type('Aqui')
      cy.get('#street2').type('2')
      cy.get('#city').type('Lejos')
      cy.get('#stateProvince').type('de Aqui')
      cy.get('#postalCode').type('56002')
      cy.get('#country').type('Fuera')
      cy.get('#submit').click()

      cy.contains('User2' + random + ' Test2').click()
      cy.get('#firstName').should('contain', `User2${random}`)
      cy.get('#lastName').should('contain', 'Test2')
      cy.get('#birthdate').should('contain', '2000-10-28')
      cy.get('#email').should('contain', 'user2test@fake.com')
      cy.get('#phone').should('contain', '665983655')
      cy.get('#street1').should('contain', 'Aqui')
      cy.get('#street2').should('contain', '2')
      cy.get('#city').should('contain', 'Lejos')
      cy.get('#stateProvince').should('contain', 'de Aqui')
      cy.get('#postalCode').should('contain', '56002')
      cy.get('#country').should('contain', 'Fuera')

      cy.get('#delete').click()
      cy.on('window:confirm', () => true)
    })
  })